// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $admin_login from "./routes/admin/login.tsx";
import * as $api_items from "./routes/api/items.ts";
import * as $api_upload from "./routes/api/upload.ts";
import * as $index from "./routes/index.tsx";
import * as $uploads_name_ from "./routes/uploads/[name].ts";
import * as $AdminForm from "./islands/AdminForm.tsx";
import * as $AdminItemsList from "./islands/AdminItemsList.tsx";
import * as $CatalogExplorer from "./islands/CatalogExplorer.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/admin/login.tsx": $admin_login,
    "./routes/api/items.ts": $api_items,
    "./routes/api/upload.ts": $api_upload,
    "./routes/index.tsx": $index,
    "./routes/uploads/[name].ts": $uploads_name_,
  },
  islands: {
    "./islands/AdminForm.tsx": $AdminForm,
    "./islands/AdminItemsList.tsx": $AdminItemsList,
    "./islands/CatalogExplorer.tsx": $CatalogExplorer,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
