// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source control.
// This file is automatically updated during development when running `dev.ts`.

import * as $routes_app from "./routes/_app.tsx";
import * as $routes_index from "./routes/index.tsx";
import * as $routes_admin_index from "./routes/admin/index.tsx";
import * as $routes_admin_login from "./routes/admin/login.tsx";
import * as $routes_api_items from "./routes/api/items.ts";
import * as $routes_api_upload from "./routes/api/upload.ts";
import * as $routes_uploads_name from "./routes/uploads/[name].ts";

import * as $islands_CatalogExplorer from "./islands/CatalogExplorer.tsx";
import * as $islands_AdminForm from "./islands/AdminForm.tsx";
import * as $islands_AdminItemsList from "./islands/AdminItemsList.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $routes_app,
    "./routes/index.tsx": $routes_index,
    "./routes/admin/index.tsx": $routes_admin_index,
    "./routes/admin/login.tsx": $routes_admin_login,
    "./routes/api/items.ts": $routes_api_items,
    "./routes/api/upload.ts": $routes_api_upload,
    "./routes/uploads/[name].ts": $routes_uploads_name,
  },
  islands: {
    "./islands/CatalogExplorer.tsx": $islands_CatalogExplorer,
    "./islands/AdminForm.tsx": $islands_AdminForm,
    "./islands/AdminItemsList.tsx": $islands_AdminItemsList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
